/**
 * FileProtection — 非 AutoSnippet 独有文件的写入保护
 *
 * 保护逻辑：
 *   - 如果目标文件不存在 → 直接写入（首次生成）
 *   - 如果目标文件存在且包含 AutoSnippet 签名 → 允许覆盖（我们生成的）
 *   - 如果目标文件存在但不包含 AutoSnippet 签名 → 拒绝覆盖（用户原有文件）
 *
 * 签名标记（任意一个匹配即视为 AutoSnippet 所有）：
 *   - "Auto-generated by AutoSnippet"
 *   - "Auto-generated by [AutoSnippet]"
 *   - "auto-generated by autosnippet" (case-insensitive)
 */

import fs from 'node:fs';

/**
 * AutoSnippet 文件签名模式（case-insensitive）
 * 检查文件前 1024 字节即可——签名总在文件头部
 */
const SIGNATURE_PATTERN = /auto-generated by (?:\[)?autosnippet(?:\])?/i;

/**
 * 检查文件是否可以被 AutoSnippet 安全写入
 *
 * @param {string} filePath - 目标文件绝对路径
 * @returns {{ canWrite: boolean, reason: string }}
 *   - canWrite: true  → 可以安全写入
 *   - canWrite: false → 文件存在且非 AutoSnippet 生成，不应覆盖
 */
export function checkWriteSafety(filePath) {
  if (!fs.existsSync(filePath)) {
    return { canWrite: true, reason: 'file-not-exist' };
  }

  try {
    // 只读前 1024 字节检测签名，避免大文件全量读取
    const fd = fs.openSync(filePath, 'r');
    const buf = Buffer.alloc(1024);
    const bytesRead = fs.readSync(fd, buf, 0, 1024, 0);
    fs.closeSync(fd);

    const header = buf.toString('utf8', 0, bytesRead);
    if (SIGNATURE_PATTERN.test(header)) {
      return { canWrite: true, reason: 'autosnippet-owned' };
    }

    return { canWrite: false, reason: 'user-owned' };
  } catch {
    // 读取失败（权限等问题），保守处理：不覆盖
    return { canWrite: false, reason: 'read-error' };
  }
}

/**
 * 安全写入文件 — 带保护机制
 *
 * @param {string} filePath - 目标文件绝对路径
 * @param {string} content - 文件内容
 * @param {Object} [options]
 * @param {boolean} [options.force=false] - 强制覆盖（忽略保护）
 * @param {Object} [options.logger] - 日志器
 * @returns {{ written: boolean, reason: string, filePath: string }}
 */
export function safeWriteFile(filePath, content, options = {}) {
  const { force = false, logger } = options;

  if (force) {
    fs.writeFileSync(filePath, content, 'utf8');
    return { written: true, reason: 'force', filePath };
  }

  const { canWrite, reason } = checkWriteSafety(filePath);

  if (canWrite) {
    fs.writeFileSync(filePath, content, 'utf8');
    return { written: true, reason, filePath };
  }

  // 用户原有文件 → 跳过
  logger?.info?.(
    `[FileProtection] Skipped "${filePath}" — ${reason} (file exists and is not AutoSnippet-generated)`
  );
  return { written: false, reason, filePath };
}

/**
 * 安全复制文件 — 带保护机制
 *
 * @param {string} srcPath - 源文件路径
 * @param {string} destPath - 目标文件路径
 * @param {Object} [options]
 * @param {boolean} [options.force=false] - 强制覆盖
 * @param {Object} [options.logger] - 日志器
 * @returns {{ written: boolean, reason: string, filePath: string }}
 */
export function safeCopyFile(srcPath, destPath, options = {}) {
  const { force = false, logger } = options;

  if (force) {
    fs.copyFileSync(srcPath, destPath);
    return { written: true, reason: 'force', filePath: destPath };
  }

  const { canWrite, reason } = checkWriteSafety(destPath);

  if (canWrite) {
    fs.copyFileSync(srcPath, destPath);
    return { written: true, reason, filePath: destPath };
  }

  logger?.info?.(
    `[FileProtection] Skipped "${destPath}" — ${reason} (file exists and is not AutoSnippet-generated)`
  );
  return { written: false, reason, filePath: destPath };
}
