/**
 * RulesGenerator — .mdc 文件生成器
 *
 * 生成 Cursor Rules 格式的 .mdc 文件到 .cursor/rules/ 目录：
 *   - Channel A: autosnippet-project-rules.mdc (alwaysApply: true)
 *   - Channel B: autosnippet-patterns-{topic}.mdc (alwaysApply: false)
 */

import fs from 'node:fs';
import path from 'node:path';
import { estimateTokens, BUDGET } from './TokenBudget.js';

export class RulesGenerator {
  /**
   * @param {string} projectRoot - 用户项目根目录
   * @param {string} projectName - 项目名称（用于 description/标题）
   */
  constructor(projectRoot, projectName = 'Project') {
    this.projectRoot = projectRoot;
    this.projectName = projectName;
    this.rulesDir = path.join(projectRoot, '.cursor', 'rules');
  }

  /**
   * Channel A — 写入 Always-On Rules 文件
   *
   * @param {string[]} ruleLines - 一行式规则列表 (来自 KnowledgeCompressor.compressToRuleLine)
   * @returns {{ filePath: string, tokensUsed: number, rulesCount: number }}
   */
  writeAlwaysOnRules(ruleLines) {
    this._ensureDir();

    // Token 预算控制
    const kept = [];
    let tokens = 0;
    const headerFooterBudget = 100;
    const ruleBudget = BUDGET.CHANNEL_A_MAX - headerFooterBudget;

    for (const line of ruleLines) {
      const lineTokens = estimateTokens(line);
      if (tokens + lineTokens <= ruleBudget && kept.length < BUDGET.CHANNEL_A_MAX_RULES) {
        kept.push(line);
        tokens += lineTokens;
      }
    }

    const content = this._renderChannelA(kept);
    const filePath = path.join(this.rulesDir, 'autosnippet-project-rules.mdc');
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      filePath,
      tokensUsed: estimateTokens(content),
      rulesCount: kept.length,
    };
  }

  /**
   * Channel B — 写入 Smart Rules 文件（按主题）
   *
   * @param {string} topic - 主题名 (networking, ui, data, architecture, conventions, general)
   * @param {string} compressedContent - 格式化后的 When/Do/Don't Markdown 内容
   * @param {string} description - Agent 关联性判断用 description
   * @returns {{ filePath: string, tokensUsed: number }}
   */
  writeSmartRules(topic, compressedContent, description) {
    this._ensureDir();

    // Token 预算控制
    let body = compressedContent;
    const totalTokens = estimateTokens(body) + estimateTokens(description) + 50;
    if (totalTokens > BUDGET.CHANNEL_B_MAX_PER_FILE) {
      // 截断尾部
      const lines = body.split('\n');
      const truncated = [];
      let used = estimateTokens(description) + 50;
      for (const line of lines) {
        used += estimateTokens(line + '\n');
        if (used <= BUDGET.CHANNEL_B_MAX_PER_FILE) {
          truncated.push(line);
        }
      }
      body = truncated.join('\n');
    }

    const content = this._renderChannelB(topic, body, description);
    const fileName = `autosnippet-patterns-${topic}.mdc`;
    const filePath = path.join(this.rulesDir, fileName);
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      filePath,
      tokensUsed: estimateTokens(content),
    };
  }

  /**
   * 清理旧的动态生成文件
   * 保留静态模板文件（autosnippet-conventions.mdc, autosnippet-skills.mdc）
   */
  cleanDynamicFiles() {
    if (!fs.existsSync(this.rulesDir)) return;

    const dynamicPrefixes = ['autosnippet-project-rules', 'autosnippet-patterns-'];
    const files = fs.readdirSync(this.rulesDir);
    for (const file of files) {
      if (dynamicPrefixes.some(p => file.startsWith(p))) {
        const filePath = path.join(this.rulesDir, file);
        try { fs.unlinkSync(filePath); } catch { /* ignore */ }
      }
    }
  }

  // ─── 渲染方法 ───────────────────────────────────────

  /**
   * @private
   */
  _renderChannelA(ruleLines) {
    const desc = `${this.projectName} mandatory rules — coding constraints that must never be violated. Auto-generated by AutoSnippet.`;
    const lines = [
      '---',
      `description: "${desc}"`,
      'alwaysApply: true',
      '---',
      '',
      `# ${this.projectName} — Mandatory Rules`,
      '',
      ...ruleLines,
      '',
      'For detailed patterns and recipes, AutoSnippet MCP tools are available:',
      '- `autosnippet_search(query)` — search knowledge base',
      '- `autosnippet_context_search(query)` — context-aware search with history',
    ];
    return lines.join('\n') + '\n';
  }

  /**
   * @private
   */
  _renderChannelB(topic, body, description) {
    const topicLabel = topic.charAt(0).toUpperCase() + topic.slice(1);
    const lines = [
      '---',
      `description: "${description}"`,
      'alwaysApply: false',
      '---',
      '',
      `# ${topicLabel} Patterns`,
      '',
      body,
      '',
      `For full code examples: \`autosnippet_search("${topic}")\``,
    ];
    return lines.join('\n') + '\n';
  }

  /**
   * @private
   */
  _ensureDir() {
    if (!fs.existsSync(this.rulesDir)) {
      fs.mkdirSync(this.rulesDir, { recursive: true });
    }
  }
}

export default RulesGenerator;
