import type {
  EngineeringWorkflowGuardRuleFact,
  EngineeringWorkflowOptionalDimension,
} from "./EngineeringWorkflowOptionalTypes.js";

export interface EngineeringWorkflowEnhancementPackDefinition {
  readonly id: string;
  readonly displayName: string;
  readonly languages: readonly string[];
  readonly frameworks: readonly string[];
  readonly aliases: readonly string[];
  readonly fileHints: readonly RegExp[];
  readonly roleHints: readonly RegExp[];
  readonly dimensions: readonly EngineeringWorkflowOptionalDimension[];
  readonly guardRules: readonly EngineeringWorkflowGuardRuleFact[];
  readonly patternTypes: readonly string[];
}

export const LEGACY_ENHANCEMENT_PACKS: readonly EngineeringWorkflowEnhancementPackDefinition[] = [
  pack({
    id: "react",
    displayName: "React 19 Enhancement",
    languages: ["typescript", "javascript"],
    frameworks: ["react", "nextjs"],
    aliases: ["react", "react-dom", "jsx", "tsx", "zustand", "jotai", "@reduxjs"],
    fileHints: [/\.tsx$/, /(^|\/)components?\//, /(^|\/)hooks?\//],
    roleHints: [/front.?end/i, /ui/i, /component/i],
    dimensions: [
      dimension("hook-pattern-scan", "Custom Hook analysis", ["code-pattern"], "react"),
      dimension(
        "component-structure-scan",
        "Component structure conventions",
        ["code-standard", "architecture"],
        "react",
      ),
      dimension(
        "rsc-boundary-scan",
        "Server/client boundary analysis",
        ["architecture", "code-pattern"],
        "react",
      ),
      dimension(
        "state-management-scan",
        "State management analysis",
        ["architecture", "code-pattern"],
        "react",
      ),
    ],
    guardRules: [
      rule(
        "react-no-direct-dom",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /document\.(getElementById|querySelector|getElementsBy)/,
        "Avoid direct DOM operations in React components.",
      ),
      rule(
        "react-hooks-conditional",
        "correctness",
        "file",
        "error",
        ["typescript", "javascript"],
        /if\s*\([^)]*\)\s*\{[^}]*\buse[A-Z]\w*\s*\(/,
        "Hooks must not be called conditionally.",
      ),
      rule(
        "react-exhaustive-deps",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /\/\/\s*eslint-disable.*exhaustive-deps/,
        "Avoid suppressing exhaustive-deps without a documented alternative.",
      ),
    ],
    patternTypes: [
      "custom-hook",
      "hoc",
      "react-component",
      "react-context-provider",
      "react-store",
      "react-ecosystem-usage",
    ],
  }),
  pack({
    id: "nextjs",
    displayName: "Next.js 15 App Router Enhancement",
    languages: ["typescript", "javascript"],
    frameworks: ["nextjs"],
    aliases: ["next", "nextjs", "next/navigation", "next/server", "app-router"],
    fileHints: [/next\.config\.[cm]?[jt]s$/, /(^|\/)app\/.*(page|layout|route)\.[jt]sx?$/],
    roleHints: [/front.?end/i, /web/i],
    dimensions: [
      dimension("nextjs-app-router-scan", "App Router structure", ["architecture"], "nextjs"),
      dimension(
        "nextjs-server-action-scan",
        "Server Action boundaries",
        ["architecture", "code-pattern"],
        "nextjs",
      ),
      dimension("nextjs-cache-scan", "Fetch and cache policy", ["code-standard"], "nextjs"),
    ],
    guardRules: [
      rule(
        "nextjs-no-window-in-server",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /(?:^|\n)(?!['"]use client['"])[\s\S]*\bwindow\./,
        "Server components should not access window directly.",
      ),
      rule(
        "nextjs-metadata-with-use-client",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /['"]use client['"][\s\S]*export\s+const\s+metadata/,
        "Client components cannot export metadata.",
      ),
    ],
    patternTypes: [
      "nextjs-app-router-component",
      "nextjs-route-handler",
      "nextjs-server-action",
      "nextjs-framework-usage",
    ],
  }),
  pack({
    id: "vue",
    displayName: "Vue 3.5 / Nuxt Enhancement",
    languages: ["typescript", "javascript"],
    frameworks: ["vue", "nuxt"],
    aliases: ["vue", "nuxt", "pinia", "@vue", "vue-router"],
    fileHints: [/\.vue$/, /nuxt\.config\.[jt]s$/, /(^|\/)composables?\//],
    roleHints: [/front.?end/i, /ui/i],
    dimensions: [
      dimension("vue-composable-scan", "Vue composable patterns", ["code-pattern"], "vue"),
      dimension("vue-sfc-scan", "SFC structure", ["code-standard"], "vue"),
      dimension("vue-router-store-scan", "Router and Pinia topology", ["architecture"], "vue"),
    ],
    guardRules: [
      rule(
        "vue-no-v-html",
        "safety",
        "file",
        "warning",
        ["typescript", "javascript"],
        /v-html\s*=/,
        "Avoid v-html unless content is sanitized.",
      ),
      rule(
        "vue-v-for-with-v-if",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /v-for=.*v-if=|v-if=.*v-for=/,
        "Avoid using v-if and v-for on the same element.",
      ),
    ],
    patternTypes: ["vue-composable", "vue-pinia-store", "vue-router-guard", "vue-plugin"],
  }),
  pack({
    id: "node-server",
    displayName: "Node.js Server Enhancement",
    languages: ["typescript", "javascript"],
    frameworks: ["node-server", "nestjs"],
    aliases: ["express", "fastify", "@nestjs", "koa", "hono", "node:http", "zod", "joi"],
    fileHints: [/server\.[cm]?[jt]s$/, /(^|\/)(routes?|controllers?|middleware)\//],
    roleHints: [/server/i, /api/i, /backend/i],
    dimensions: [
      dimension(
        "middleware-analysis",
        "Middleware chain analysis",
        ["architecture", "code-pattern"],
        "node-server",
      ),
      dimension("nestjs-module-scan", "NestJS module DI analysis", ["architecture"], "node-server"),
      dimension(
        "node-validation-scan",
        "Request validation patterns",
        ["code-pattern", "code-standard"],
        "node-server",
      ),
    ],
    guardRules: [
      rule(
        "node-no-sync-io",
        "performance",
        "file",
        "warning",
        ["typescript", "javascript"],
        /(?:readFileSync|writeFileSync|appendFileSync|mkdirSync|readdirSync|statSync|existsSync|unlinkSync|renameSync|copyFileSync|accessSync)/,
        "Avoid synchronous IO in request paths.",
      ),
      rule(
        "node-no-unhandled-promise",
        "correctness",
        "file",
        "warning",
        ["typescript", "javascript"],
        /\.then\s*\([^)]*\)\s*(?!\.catch)/,
        "Promise chains should handle rejection.",
      ),
      rule(
        "node-exposed-secrets",
        "safety",
        "file",
        "error",
        ["typescript", "javascript"],
        /(?:password|secret|api[_-]?key|token)\s*[:=]\s*['"][^'"]+['"]/i,
        "Hard-coded secrets should be moved to environment or secret storage.",
      ),
    ],
    patternTypes: [
      "middleware",
      "nestjs-controller",
      "nestjs-module",
      "fastify-plugin",
      "node-dto",
      "node-server-framework-usage",
    ],
  }),
  pack({
    id: "django",
    displayName: "Django / DRF Enhancement",
    languages: ["python"],
    frameworks: ["django"],
    aliases: ["django", "rest_framework", "celery", "channels"],
    fileHints: [/(^|\/)(models|views|serializers|admin)\.py$/, /manage\.py$/],
    roleHints: [/backend/i, /api/i],
    dimensions: [
      dimension(
        "django-model-scan",
        "Django model and migration patterns",
        ["architecture", "code-pattern"],
        "django",
      ),
      dimension("django-view-scan", "View and DRF serializer patterns", ["code-pattern"], "django"),
      dimension(
        "django-async-task-scan",
        "Signals, tasks, and async work",
        ["architecture"],
        "django",
      ),
    ],
    guardRules: [
      rule(
        "django-raw-sql",
        "safety",
        "file",
        "warning",
        ["python"],
        /\.raw\(|RawSQL\(|cursor\.execute\(/,
        "Raw SQL should be parameterized and isolated.",
      ),
      rule(
        "django-no-null-charfield",
        "correctness",
        "file",
        "warning",
        ["python"],
        /models\.(?:CharField|TextField)\([^)]*null=True/,
        "Prefer blank=True over null=True for text fields.",
      ),
    ],
    patternTypes: [
      "django-model",
      "django-view",
      "drf-serializer",
      "django-management-command",
      "django-celery-task",
    ],
  }),
  pack({
    id: "fastapi",
    displayName: "FastAPI Enhancement",
    languages: ["python"],
    frameworks: ["fastapi"],
    aliases: ["fastapi", "pydantic", "sqlalchemy", "tortoise", "uvicorn"],
    fileHints: [/(^|\/)(routers?|api)\//, /main\.py$/],
    roleHints: [/api/i, /backend/i],
    dimensions: [
      dimension(
        "fastapi-route-scan",
        "FastAPI route analysis",
        ["architecture", "code-pattern"],
        "fastapi",
      ),
      dimension(
        "fastapi-middleware-scan",
        "FastAPI middleware analysis",
        ["architecture", "code-pattern"],
        "fastapi",
      ),
      dimension(
        "fastapi-orm-scan",
        "ORM and DB patterns",
        ["architecture", "code-pattern"],
        "fastapi",
      ),
    ],
    guardRules: [
      rule(
        "fastapi-sync-in-async",
        "performance",
        "file",
        "warning",
        ["python"],
        /async\s+def\s+\w+[\s\S]*?(?:time\.sleep|open\(|os\.read|subprocess\.run)/,
        "Avoid blocking operations in async FastAPI routes.",
      ),
      rule(
        "fastapi-bare-except",
        "correctness",
        "file",
        "warning",
        ["python"],
        /except\s*:/,
        "Avoid bare except in request paths.",
      ),
      rule(
        "fastapi-no-star-import",
        "style",
        "file",
        "warning",
        ["python"],
        /from\s+\w+\s+import\s+\*/,
        "Avoid star imports.",
      ),
    ],
    patternTypes: [
      "pydantic-model",
      "fastapi-route",
      "fastapi-dependency",
      "sqlalchemy-model",
      "fastapi-ecosystem-usage",
    ],
  }),
  pack({
    id: "spring",
    displayName: "Spring Boot Enhancement",
    languages: ["java", "kotlin"],
    frameworks: ["spring"],
    aliases: ["spring", "springframework", "spring-boot", "jpa", "hibernate"],
    fileHints: [/Application\.(java|kt)$/, /(^|\/)(controller|service|repository)\//i],
    roleHints: [/backend/i, /service/i],
    dimensions: [
      dimension("spring-bean-scan", "Spring bean topology", ["architecture"], "spring"),
      dimension(
        "spring-data-scan",
        "JPA and repository patterns",
        ["architecture", "code-pattern"],
        "spring",
      ),
    ],
    guardRules: [
      rule(
        "spring-field-injection",
        "style",
        "file",
        "warning",
        ["java", "kotlin"],
        /@Autowired\s+(?:private|lateinit)/,
        "Prefer constructor injection over field injection.",
      ),
    ],
    patternTypes: ["spring-rest-controller", "spring-service", "spring-repository", "jpa-entity"],
  }),
  pack({
    id: "android",
    displayName: "Android Enhancement",
    languages: ["kotlin", "java"],
    frameworks: ["android"],
    aliases: ["android", "androidx", "compose", "hilt", "gradle"],
    fileHints: [/AndroidManifest\.xml$/, /(^|\/)(res|app\/src\/main)\//, /\.kt$/],
    roleHints: [/mobile/i, /android/i],
    dimensions: [
      dimension(
        "android-architecture-scan",
        "Android architecture patterns",
        ["architecture", "code-pattern"],
        "android",
      ),
      dimension("android-compose-scan", "Compose UI patterns", ["code-pattern"], "android"),
    ],
    guardRules: [],
    patternTypes: [
      "android-viewmodel",
      "android-activity",
      "android-fragment",
      "composable",
      "hilt-di",
    ],
  }),
  pack({
    id: "rust-web",
    displayName: "Rust Web Enhancement",
    languages: ["rust"],
    frameworks: ["actix-web", "axum", "rocket", "warp"],
    aliases: ["actix_web", "actix-web", "axum", "rocket", "warp", "tower", "tower_http"],
    fileHints: [/Cargo\.toml$/, /(^|\/)(routes?|handlers?)\//],
    roleHints: [/api/i, /backend/i],
    dimensions: [
      dimension(
        "rust-handler-scan",
        "Rust HTTP handler analysis",
        ["architecture", "code-pattern"],
        "rust-web",
      ),
      dimension("rust-route-scan", "Rust route structure", ["architecture"], "rust-web"),
    ],
    guardRules: [
      rule(
        "rust-web-unwrap-in-handler",
        "correctness",
        "file",
        "warning",
        ["rust"],
        /\.unwrap\(\)/,
        "Avoid unwrap in web handlers.",
      ),
      rule(
        "rust-web-blocking-in-async",
        "performance",
        "file",
        "warning",
        ["rust"],
        /std::fs::|std::net::|std::thread::sleep/,
        "Avoid blocking std operations in async handlers.",
      ),
    ],
    patternTypes: [
      "rust-web-handler",
      "rust-web-state",
      "rust-web-middleware",
      "rust-web-framework-usage",
    ],
  }),
  pack({
    id: "rust-tokio",
    displayName: "Rust Tokio/Async Enhancement",
    languages: ["rust"],
    frameworks: ["tokio", "async-std"],
    aliases: ["tokio", "async_std", "async-std", "futures", "tracing"],
    fileHints: [/Cargo\.toml$/, /(^|\/)(workers?|tasks?)\//],
    roleHints: [/worker/i, /backend/i],
    dimensions: [
      dimension(
        "rust-async-runtime-scan",
        "Rust async runtime patterns",
        ["architecture", "code-pattern"],
        "rust-tokio",
      ),
      dimension("rust-channel-scan", "Channel and worker topology", ["architecture"], "rust-tokio"),
    ],
    guardRules: [
      rule(
        "rust-tokio-std-mutex",
        "performance",
        "file",
        "warning",
        ["rust"],
        /std::sync::Mutex/,
        "Avoid std::sync::Mutex across async await points.",
      ),
      rule(
        "rust-tokio-blocking-in-async",
        "performance",
        "file",
        "warning",
        ["rust"],
        /std::thread::sleep|std::fs::/,
        "Use Tokio async alternatives for blocking work.",
      ),
    ],
    patternTypes: [
      "rust-async-functions",
      "rust-tokio-main",
      "rust-async-worker",
      "rust-channel-struct",
    ],
  }),
  pack({
    id: "go-web",
    displayName: "Go Web Enhancement",
    languages: ["go"],
    frameworks: ["gin", "echo", "fiber", "chi", "gorilla", "beego"],
    aliases: ["gin-gonic", "gin", "labstack/echo", "gofiber", "go-chi", "gorilla/mux", "beego"],
    fileHints: [/(^|\/)(handlers?|routes?|middleware)\//, /\.go$/],
    roleHints: [/api/i, /backend/i],
    dimensions: [
      dimension(
        "go-handler-scan",
        "Go handler and middleware patterns",
        ["architecture", "code-pattern"],
        "go-web",
      ),
      dimension("go-router-scan", "Go route topology", ["architecture"], "go-web"),
    ],
    guardRules: [
      rule(
        "go-handler-abort-return",
        "correctness",
        "file",
        "warning",
        ["go"],
        /AbortWithStatus(?:JSON)?\([^)]*\)\s*\n\s*(?!return)/,
        "Gin abort calls should return immediately.",
      ),
      rule(
        "go-no-naked-goroutine",
        "correctness",
        "file",
        "warning",
        ["go"],
        /\bgo\s+func\s*\(/,
        "Naked goroutines should have lifecycle and error handling.",
      ),
    ],
    patternTypes: ["go-handler-struct", "go-handler-method", "go-middleware", "go-router-core"],
  }),
  pack({
    id: "go-grpc",
    displayName: "Go gRPC Enhancement",
    languages: ["go"],
    frameworks: ["grpc"],
    aliases: ["grpc", "google.golang.org/grpc", "protobuf", "proto"],
    fileHints: [/\.proto$/, /pb\.go$/, /grpc/],
    roleHints: [/rpc/i, /service/i],
    dimensions: [
      dimension(
        "go-grpc-service-scan",
        "Go gRPC service patterns",
        ["architecture", "code-pattern"],
        "go-grpc",
      ),
      dimension("go-grpc-interceptor-scan", "Interceptor topology", ["architecture"], "go-grpc"),
    ],
    guardRules: [
      rule(
        "go-grpc-status-error",
        "correctness",
        "file",
        "warning",
        ["go"],
        /return\s+err(?!or)/,
        "gRPC handlers should return status errors with codes when possible.",
      ),
    ],
    patternTypes: ["go-grpc-service-impl", "go-grpc-interceptor", "go-grpc-proto-usage"],
  }),
  pack({
    id: "python-ml",
    displayName: "Python AI/ML Enhancement",
    languages: ["python"],
    frameworks: ["ml"],
    aliases: ["torch", "pytorch", "tensorflow", "sklearn", "transformers", "datasets", "numpy"],
    fileHints: [/(^|\/)(train|models?|datasets?|notebooks?)\//, /train.*\.py$/],
    roleHints: [/ml/i, /model/i, /data/i],
    dimensions: [
      dimension("ml-model-scan", "Model and dataset patterns", ["code-pattern"], "python-ml"),
      dimension(
        "ml-training-scan",
        "Training and evaluation loops",
        ["architecture", "code-standard"],
        "python-ml",
      ),
    ],
    guardRules: [
      rule(
        "ml-missing-no-grad",
        "performance",
        "file",
        "warning",
        ["python"],
        /model\.eval\(\)(?![\s\S]*torch\.no_grad)/,
        "Evaluation should usually run under torch.no_grad().",
      ),
      rule(
        "ml-random-seed",
        "reproducibility",
        "file",
        "info",
        ["python"],
        /random_split\(|shuffle=True/,
        "Randomized training paths should document seed policy.",
      ),
    ],
    patternTypes: [
      "pytorch-model",
      "pytorch-dataset",
      "huggingface-model",
      "ml-training-function",
      "ml-ecosystem-usage",
    ],
  }),
  pack({
    id: "python-langchain",
    displayName: "LangChain / Agent Enhancement",
    languages: ["python", "typescript", "javascript"],
    frameworks: ["langchain"],
    aliases: ["langchain", "langgraph", "@langchain", "openai", "chatopenai"],
    fileHints: [/(^|\/)(agents?|chains?|prompts?)\//],
    roleHints: [/agent/i, /llm/i, /ai/i],
    dimensions: [
      dimension(
        "langchain-chain-scan",
        "Chain and graph topology",
        ["architecture", "code-pattern"],
        "python-langchain",
      ),
      dimension(
        "langchain-safety-scan",
        "Prompt and tool safety",
        ["code-standard"],
        "python-langchain",
      ),
    ],
    guardRules: [
      rule(
        "langchain-prompt-injection",
        "safety",
        "file",
        "warning",
        ["python", "typescript", "javascript"],
        /system.*\{.*user|prompt.*\+.*input/i,
        "Prompt composition should guard untrusted user input.",
      ),
      rule(
        "langchain-hardcoded-api-key",
        "safety",
        "file",
        "error",
        ["python", "typescript", "javascript"],
        /(?:OPENAI_API_KEY|api_key)\s*=\s*['"][^'"]+['"]/,
        "Avoid hard-coded LLM API keys.",
      ),
    ],
    patternTypes: ["langchain-chain", "langchain-tool", "langchain-setup", "langgraph-node"],
  }),
];

function pack(
  definition: EngineeringWorkflowEnhancementPackDefinition,
): EngineeringWorkflowEnhancementPackDefinition {
  return definition;
}

function dimension(
  id: string,
  label: string,
  knowledgeTypes: readonly string[],
  source: string,
): EngineeringWorkflowOptionalDimension {
  return {
    id,
    label,
    knowledgeTypes,
    tierHint: 2,
    skillWorthy: true,
    dualOutput: true,
    source,
  };
}

function rule(
  ruleId: string,
  category: string,
  dimensionName: string,
  severity: EngineeringWorkflowGuardRuleFact["severity"],
  languages: readonly string[],
  pattern: RegExp,
  message: string,
): EngineeringWorkflowGuardRuleFact {
  return {
    ruleId,
    category,
    dimension: dimensionName,
    severity,
    languages,
    pattern,
    message,
    source: "legacy-enhancement",
  };
}
