import type {
  ToolDefinition,
  ToolName,
  ToolRegistryReader,
  ToolResource,
  ToolSchema,
} from "./types.js";

const objectOutputSchema: ToolSchema = {
  type: "object",
  additionalProperties: true,
};

const filePathProperty: ToolSchema = { type: "string", description: "Project-relative path." };

// 中文注释：这是内部 Agent action space 的单一清单，不兼容 legacy V1/V2，
// 也不会被 Codex MCP public tools 直接复用。
const TOOL_DEFINITIONS: readonly ToolDefinition[] = [
  {
    name: "code.search",
    resource: "code",
    action: "search",
    title: "Code Search",
    description: "Searches project files with literal or regex patterns.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    maxOutputTokens: 3_000,
    inputSchema: {
      type: "object",
      properties: {
        patterns: {
          type: "array",
          items: { type: "string" },
          description: "Search patterns. Maximum 10.",
        },
        glob: { type: "string", description: "Simple file suffix or wildcard filter." },
        pattern: { type: "string", description: "Single search pattern alias." },
        maxResults: { type: "integer", minimum: 1, maximum: 50, default: 10 },
        contextLines: { type: "integer", minimum: 0, maximum: 8, default: 2 },
        regex: { type: "boolean", default: false },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { source: "agent-tool-layer" },
  },
  {
    name: "code.read",
    resource: "code",
    action: "read",
    title: "Code Read",
    description: "Reads a project file with optional line range and safe path checks.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    maxOutputTokens: 5_000,
    inputSchema: {
      type: "object",
      properties: {
        path: filePathProperty,
        startLine: { type: "integer", minimum: 1 },
        endLine: { type: "integer", minimum: 1 },
      },
      required: ["path"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { source: "agent-tool-layer" },
  },
  {
    name: "code.outline",
    resource: "code",
    action: "outline",
    title: "Code Outline",
    description: "Extracts a lightweight symbol outline from a source file.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    maxOutputTokens: 2_000,
    inputSchema: {
      type: "object",
      properties: {
        path: filePathProperty,
        kinds: { type: "array", items: { type: "string" } },
        maxDepth: { type: "integer", minimum: 1, maximum: 8, default: 4 },
      },
      required: ["path"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { source: "agent-tool-layer" },
  },
  {
    name: "code.structure",
    resource: "code",
    action: "structure",
    title: "Code Structure",
    description: "Lists project directory structure as a compact tree.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    maxOutputTokens: 2_000,
    inputSchema: {
      type: "object",
      properties: {
        directory: { type: "string", description: "Project-relative directory." },
        depth: { type: "integer", minimum: 1, maximum: 5, default: 3 },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { source: "agent-tool-layer" },
  },
  {
    name: "code.write",
    resource: "code",
    action: "write",
    title: "Code Write",
    description: "Creates or overwrites project files after path-scope checks.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "exclusive",
    inputSchema: {
      type: "object",
      properties: {
        path: filePathProperty,
        content: { type: "string" },
        createDirectories: { type: "boolean", default: false },
      },
      required: ["path", "content"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { protectedPaths: [".git", "node_modules", ".env"] },
  },
  {
    name: "code.guard",
    resource: "code",
    action: "guard",
    title: "Code Guard",
    description: "Checks supplied code files against mainline guard-rule Recipes.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        files: {
          type: "array",
          items: {
            type: "object",
            properties: {
              path: { type: "string" },
              content: { type: "string" },
              language: { type: "string" },
              isTest: { type: "boolean" },
            },
            required: ["path", "content"],
            additionalProperties: false,
          },
        },
        maxFindings: { type: "integer", minimum: 1, maximum: 1000, default: 200 },
        maxFindingsPerRule: { type: "integer", minimum: 1, maximum: 100, default: 20 },
      },
      required: ["files"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "MainlineGuardRuleProvider" },
  },
  {
    name: "terminal.execute",
    resource: "terminal",
    action: "execute",
    title: "Terminal Execute",
    description: "Executes a bounded shell command inside the project root with safety checks.",
    availability: { status: "available" },
    risk: "side-effect",
    concurrency: "single",
    inputSchema: {
      type: "object",
      properties: {
        command: { type: "string" },
        cwd: { type: "string" },
        timeout: { type: "integer", minimum: 1, maximum: 120000, default: 30000 },
      },
      required: ["command"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { blockedDangerousCommands: true },
  },
  {
    name: "knowledge.search",
    resource: "knowledge",
    action: "search",
    title: "Knowledge Search",
    description: "Searches compiled knowledge documents through mainline search and context ports.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        text: { type: "string" },
        kind: { type: "string", enum: ["recipe", "candidate", "all"] },
        category: { type: "string" },
        paths: { type: "array", items: { type: "string" } },
        symbols: { type: "array", items: { type: "string" } },
        kinds: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 10 },
        includeContext: { type: "boolean", default: true },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "MainlineSearchIndex+ContextIndexReader" },
  },
  {
    name: "knowledge.detail",
    resource: "knowledge",
    action: "detail",
    title: "Knowledge Detail",
    description: "Returns Recipe details and related runtime context by Recipe id.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "ContextIndexReader+RecipeLifecycleStorePort" },
  },
  {
    name: "knowledge.submit",
    resource: "knowledge",
    action: "submit",
    title: "Knowledge Submit",
    description: "Submits a Recipe candidate through an injected lifecycle store or gateway.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "single",
    inputSchema: objectOutputSchema,
    outputSchema: objectOutputSchema,
    metadata: { lifecycleWrite: true, defaultStatus: "candidate" },
  },
  {
    name: "knowledge.manage",
    resource: "knowledge",
    action: "manage",
    title: "Knowledge Manage",
    description: "Runs lifecycle management through an injected lifecycle store or repository.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "single",
    inputSchema: {
      type: "object",
      properties: {
        operation: {
          type: "string",
          enum: [
            "publish",
            "reject",
            "approve",
            "deprecate",
            "update",
            "score",
            "validate",
            "evolve",
            "skip_evolution",
          ],
        },
        id: { type: "string" },
        reason: { type: "string" },
        data: { type: "object" },
      },
      required: ["operation", "id"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { lifecycleWrite: true },
  },
  {
    name: "runtime.inject_context",
    resource: "runtime",
    action: "inject_context",
    title: "Runtime Inject Context",
    description:
      "Builds an Agent-facing knowledge injection bundle from compiled ContextIndex and SearchIndex.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    maxOutputTokens: 6_000,
    inputSchema: {
      type: "object",
      properties: {
        projectRoot: { type: "string" },
        prompt: { type: "string" },
        taskText: { type: "string" },
        activeFile: { type: "string" },
        files: { type: "array", items: { type: "string" } },
        symbols: { type: "array", items: { type: "string" } },
        diff: { type: "string" },
        commandIntent: { type: "string" },
        userFocus: { type: "string" },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "KnowledgeInjectionRunner", internalOnly: true },
  },
  {
    name: "runtime.guard_finding",
    resource: "runtime",
    action: "guard_finding",
    title: "Runtime Guard Finding",
    description:
      "Converts a guard rule, risk, and location into the mainline runtime GuardFinding contract.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        rule: { type: "object", additionalProperties: true },
        risk: { type: "object", additionalProperties: true },
        location: { type: "object", additionalProperties: true },
        message: { type: "string" },
        suggestedFix: { type: "string" },
        feedback: { type: "object", additionalProperties: true },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["rule", "risk"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "GuardFindingBuilder", internalOnly: true },
  },
  {
    name: "runtime.source_ref_repair",
    resource: "runtime",
    action: "source_ref_repair",
    title: "Runtime SourceRef Repair",
    description:
      "Reports or applies SourceRef repair against compiled runtime artifacts without legacy compatibility.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "single",
    inputSchema: {
      type: "object",
      properties: {
        apply: { type: "boolean", default: false },
        minConfidence: { type: "number", minimum: 0, maximum: 1 },
        syncMarkdown: { type: "boolean", default: true },
        includeProjectIntelligence: { type: "boolean", default: true },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "MainlineSourceRefRepairService", internalOnly: true },
  },
  {
    name: "graph.overview",
    resource: "graph",
    action: "overview",
    title: "Graph Overview",
    description: "Summarizes project intelligence artifact files, symbols, and edges.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: objectOutputSchema,
    metadata: { port: "MainlineProjectIntelligenceQueries" },
  },
  {
    name: "graph.query",
    resource: "graph",
    action: "query",
    title: "Graph Query",
    description: "Queries project intelligence graph facts through the mainline query port.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        operation: {
          type: "string",
          enum: [
            "callers",
            "callees",
            "impact",
            "dependencies",
            "cycles",
            "class",
            "protocol",
            "hierarchy",
            "overrides",
            "extensions",
            "search",
          ],
        },
        type: {
          type: "string",
          enum: [
            "callers",
            "callees",
            "impact",
            "dependencies",
            "cycles",
            "class",
            "protocol",
            "hierarchy",
            "overrides",
            "extensions",
            "search",
          ],
        },
        entity: { type: "string" },
        ref: { type: "string" },
        maxDepth: { type: "integer", minimum: 0, maximum: 8, default: 1 },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 20 },
        direction: { type: "string", enum: ["incoming", "outgoing", "both"], default: "both" },
        includeStart: { type: "boolean", default: false },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "MainlineProjectIntelligenceQueries" },
  },
  {
    name: "memory.save",
    resource: "memory",
    action: "save",
    title: "Memory Save",
    description: "Saves a finding to the Agent working memory store.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        key: { type: "string" },
        content: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        category: { type: "string" },
      },
      required: ["key", "content"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "ToolMemoryStore" },
  },
  {
    name: "memory.recall",
    resource: "memory",
    action: "recall",
    title: "Memory Recall",
    description: "Recalls Agent working memory records by query or tags.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 10 },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "ToolMemoryStore" },
  },
  {
    name: "memory.note_finding",
    resource: "memory",
    action: "note_finding",
    title: "Memory Note Finding",
    description: "Records a structured finding through the Agent memory coordinator.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        finding: { type: "string" },
        evidence: { type: "string" },
        importance: { type: "integer", minimum: 1, maximum: 10, default: 5 },
        round: { type: "integer", minimum: 1, default: 1 },
        scopeId: { type: "string" },
      },
      required: ["finding"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "ToolMemoryCoordinator" },
  },
  {
    name: "memory.get_previous_evidence",
    resource: "memory",
    action: "get_previous_evidence",
    title: "Memory Previous Evidence",
    description: "Searches evidence collected by previous Agent dimensions.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        dimId: { type: "string" },
      },
      required: ["query"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { port: "ToolMemoryCoordinator" },
  },
  {
    name: "meta.capabilities",
    resource: "meta",
    action: "capabilities",
    title: "Tool Capabilities",
    description: "Returns this tools registry with availability and schema metadata.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        includeUnavailable: { type: "boolean", default: true },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { stable: true },
  },
  {
    name: "meta.tools",
    resource: "meta",
    action: "tools",
    title: "Tool Schema",
    description: "Returns compact tool summaries or one tool's full action schema.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Optional resource or tool name." },
      },
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { runtimeOnly: true },
  },
  {
    name: "meta.plan",
    resource: "meta",
    action: "plan",
    title: "Tool Plan",
    description: "Records a structured execution plan for the current Agent run.",
    availability: { status: "available" },
    risk: "write",
    concurrency: "parallel",
    inputSchema: {
      type: "object",
      properties: {
        strategy: { type: "string" },
        steps: { type: "array", items: { type: "object", additionalProperties: true } },
      },
      required: ["steps", "strategy"],
      additionalProperties: false,
    },
    outputSchema: objectOutputSchema,
    metadata: { runtimeOnly: true },
  },
  {
    name: "meta.review",
    resource: "meta",
    action: "review",
    title: "Tool Review",
    description: "Summarizes tool registry quality and policy-gated actions for self-review.",
    availability: { status: "available" },
    risk: "read-only",
    concurrency: "parallel",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: objectOutputSchema,
    metadata: { runtimeOnly: true },
  },
] as const;

export class StaticToolRegistry implements ToolRegistryReader {
  readonly #definitionsByName: ReadonlyMap<string, ToolDefinition>;

  constructor(definitions: readonly ToolDefinition[] = TOOL_DEFINITIONS) {
    this.#definitionsByName = new Map(
      definitions.map((definition) => [definition.name, definition]),
    );
  }

  list(): ToolDefinition[] {
    return [...this.#definitionsByName.values()].map(cloneDefinition);
  }

  get(name: string): ToolDefinition | undefined {
    const definition = this.#definitionsByName.get(name);
    return definition ? cloneDefinition(definition) : undefined;
  }

  listByResource(resource: ToolResource): ToolDefinition[] {
    return this.list().filter((definition) => definition.resource === resource);
  }
}

export function createDefaultToolRegistry(): StaticToolRegistry {
  return new StaticToolRegistry();
}

export function isRegisteredToolName(name: string): name is ToolName {
  return TOOL_DEFINITIONS.some((definition) => definition.name === name);
}

function cloneDefinition(definition: ToolDefinition): ToolDefinition {
  return JSON.parse(JSON.stringify(definition)) as ToolDefinition;
}
