import type { SessionStore } from '@alembic/agent/memory';
import { createAlembicProjectSkillDeliveryReceipt } from '@alembic/core/host-agent-workflows';
import { describe, expect, test, vi } from 'vitest';
import {
  buildEffectiveSkillAnalysisText,
  consumeGenerateSkills,
  type DimensionCandidateData,
  extractSkillKeyFindings,
} from '../../lib/recipe-pipeline/generate/execution/GenerateConsumers.js';
import type { GenerateEventEmitter } from '../../lib/recipe-pipeline/generate/runtime/GenerateEventEmitter.js';

function makeCandidate(analysisText: string): DimensionCandidateData {
  return {
    analysisReport: {
      analysisText,
      referencedFiles: ['src/api.ts'],
      findings: [],
    },
    producerResult: { candidateCount: 0, toolCalls: [] },
  };
}

describe('bootstrap skill consumer', () => {
  test('extracts key findings by importance', () => {
    expect(
      extractSkillKeyFindings({
        findings: [
          { finding: 'low', importance: 1 },
          { finding: 'high', importance: 9 },
        ],
      })
    ).toEqual(['high', 'low']);
  });

  test('synthesizes short skill analysis text from findings and exploration summary', () => {
    const text = buildEffectiveSkillAnalysisText({
      dim: { id: 'api', label: 'API' },
      analysisText: 'short',
      keyFindings: ['finding one'],
      distilled: { toolCallSummary: ['read src/api.ts'] },
    });

    expect(text).toContain('## API');
    expect(text).toContain('1. finding one');
    expect(text).toContain('- read src/api.ts');
  });

  test('creates project skills and emits dimension completion', async () => {
    const generateSkillFn = vi.fn(async () => ({ success: true, skillName: 'project-api' }));
    const emitDimensionComplete = vi.fn();

    const results = await consumeGenerateSkills({
      ctx: { container: { get: vi.fn() } } as never,
      dimensions: [{ id: 'api', label: 'API', skillWorthy: true }],
      dimensionCandidates: { api: makeCandidate('short') },
      sessionStore: {
        getDimensionReport: () => ({
          findings: [{ finding: 'api finding', importance: 8 }],
          workingMemoryDistilled: { toolCallSummary: ['read_file src/api.ts'] },
        }),
      } as unknown as SessionStore,
      emitter: { emitDimensionComplete } as unknown as GenerateEventEmitter,
      generateSkillFn: generateSkillFn as never,
    });

    expect(results).toMatchObject({
      created: 1,
      failed: 0,
      skills: ['project-api'],
      errors: [],
      deliveryReceipts: [],
    });
    expect(generateSkillFn).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({ id: 'api' }),
      expect.stringContaining('api finding'),
      ['src/api.ts'],
      ['api finding'],
      'bootstrap-v3'
    );
    expect(emitDimensionComplete).toHaveBeenCalledWith('api', {
      type: 'skill',
      deliveryReceipt: undefined,
      deliveryReceiptSummary: undefined,
      deliveryReceiptValidation: undefined,
      skillName: 'project-api',
      sourceCount: 1,
    });
  });

  test('records skill delivery receipts and emits job process event payloads', async () => {
    const receipt = createAlembicProjectSkillDeliveryReceipt({
      asset: {
        contentHash: 'sha256:abc123',
        dimensionId: 'api',
        path: '/tmp/project/Alembic/skills/project-api/SKILL.md',
      },
      authorization: {
        codexSkillRoot: '/tmp/project/.agents/skills',
        projectScopeId: 'project:test',
        status: 'pending',
      },
      codexSkillRoot: '/tmp/project/.agents/skills',
      createdAt: '2026-05-24T12:00:00Z',
      dimensionId: 'api',
      id: 'receipt-api',
      managedMarker: {
        generatedSkillId: 'alembic:project:test:project-api',
        markerPath: '/tmp/project/.agents/skills/project-api/.alembic-managed.json',
      },
      projectId: 'test',
      projectRoot: '/tmp/project',
      projectScopeId: 'project:test',
      runtimeExport: {
        codexSkillRoot: '/tmp/project/.agents/skills',
        projectScopeId: 'project:test',
        refreshRequired: true,
        status: 'pending',
        targetPath: '/tmp/project/.agents/skills/project-api',
        targetRoot: '/tmp/project/.agents/skills',
      },
      skillName: 'project-api',
    });
    const generateSkillFn = vi.fn(async () => ({
      success: true,
      skillName: 'project-api',
      deliveryReceipt: receipt,
      deliveryReceiptSummary: 'Project Skill project-api generated by Alembic',
      deliveryReceiptValidation: { issues: [], ok: true, receipt },
    }));
    const emitDimensionComplete = vi.fn();
    const emitProcessEvents = vi.fn();

    const results = await consumeGenerateSkills({
      ctx: { container: { get: vi.fn() } } as never,
      dimensions: [{ id: 'api', label: 'API', skillWorthy: true }],
      dimensionCandidates: { api: makeCandidate('short') },
      sessionStore: {
        getDimensionReport: () => ({
          findings: [{ finding: 'api finding', importance: 8 }],
          workingMemoryDistilled: { toolCallSummary: ['read_file src/api.ts'] },
        }),
      } as unknown as SessionStore,
      emitter: { emitDimensionComplete, emitProcessEvents } as unknown as GenerateEventEmitter,
      sessionId: 'bs_receipt',
      generateSkillFn: generateSkillFn as never,
    });

    expect(results.deliveryReceipts).toEqual([receipt]);
    expect(results.deliveryReceiptSummaries).toEqual([
      'Project Skill project-api generated by Alembic',
    ]);
    expect(emitDimensionComplete).toHaveBeenCalledWith(
      'api',
      expect.objectContaining({
        deliveryReceipt: receipt,
        deliveryReceiptSummary: 'Project Skill project-api generated by Alembic',
        skillName: 'project-api',
      })
    );
    expect(emitProcessEvents).toHaveBeenCalledWith(
      expect.objectContaining({
        dimensionId: 'api',
        sessionId: 'bs_receipt',
        events: [
          expect.objectContaining({
            kind: 'artifact',
            phase: 'skill-delivery',
            metadata: expect.objectContaining({
              receiptId: 'receipt-api',
              runtimeExportStatus: 'pending',
              skillName: 'project-api',
            }),
          }),
        ],
      })
    );
  });

  test('records failed skill generation and respects abort checks', async () => {
    const generateSkillFn = vi.fn(async () => ({
      success: false,
      skillName: 'project-api',
      error: 'too short',
    }));
    const emitDimensionFailed = vi.fn();

    const results = await consumeGenerateSkills({
      ctx: { container: { get: vi.fn() } } as never,
      dimensions: [
        { id: 'api', skillWorthy: true },
        { id: 'ui', skillWorthy: true },
      ],
      dimensionCandidates: {
        api: makeCandidate('valid analysis '.repeat(20)),
        ui: makeCandidate('valid analysis '.repeat(20)),
      },
      sessionStore: { getDimensionReport: () => ({ findings: [] }) } as unknown as SessionStore,
      emitter: { emitDimensionFailed } as unknown as GenerateEventEmitter,
      shouldAbort: vi.fn().mockReturnValueOnce(false).mockReturnValueOnce(true),
      generateSkillFn: generateSkillFn as never,
    });

    expect(results.failed).toBe(1);
    expect(results.errors).toEqual([{ dimId: 'api', error: 'too short' }]);
    expect(generateSkillFn).toHaveBeenCalledTimes(1);
    expect(emitDimensionFailed).toHaveBeenCalledWith('api', expect.any(Error));
  });
});
