import {
  createAlembicProjectSkillDeliveryReceipt,
  type WorkflowReport,
} from '@alembic/core/host-agent-workflows';
import { describe, expect, test } from 'vitest';
import {
  augmentWorkflowReportWithEfficiency,
  augmentWorkflowReportWithPcvNodeLocalBaseline,
  augmentWorkflowReportWithSkillDeliveryReceipts,
} from '../../lib/workflows/capabilities/execution/internal-agent/InternalDimensionFillFinalizer.js';

describe('internal dimension fill finalizer efficiency report augmentation', () => {
  test('writes aggregate and per-dimension efficiency into workflow reports', () => {
    const report = {
      version: '2.7.0',
      timestamp: '2026-05-20T00:00:00.000Z',
      project: { name: 'Alembic', files: 1, lang: 'ts' },
      duration: { totalMs: 100, totalSec: 0 },
      dimensions: { api: { toolCallCount: 3 }, ui: { toolCallCount: 2 } },
      totals: { toolCalls: 5 },
      checkpoints: { restored: [] },
      incremental: null,
      semanticMemory: null,
      session: { id: 'session-1' },
    } as WorkflowReport;

    const changed = augmentWorkflowReportWithEfficiency(report, {
      api: {
        candidateCount: 1,
        durationMs: 10,
        efficiency: {
          toolCalls: 3,
          duplicateToolCalls: 1,
          cacheHits: 2,
          cacheMisses: 1,
          tokenUsage: { input: 10, output: 4, reasoning: 2, cacheHit: 3 },
          maxCompactionLevel: 1,
          totalCompactedItems: 2,
          nudgeCount: 1,
          replanCount: 0,
          emptyRetries: 1,
          forcedSummary: false,
        },
      },
      ui: {
        candidateCount: 0,
        durationMs: 10,
        efficiency: {
          toolCalls: 2,
          duplicateToolCalls: 0,
          cacheHits: 1,
          cacheMisses: 1,
          tokenUsage: { input: 8, output: 3, reasoning: 1, cacheHit: 2 },
          maxCompactionLevel: 2,
          totalCompactedItems: 3,
          nudgeCount: 0,
          replanCount: 1,
          emptyRetries: 0,
          forcedSummary: true,
        },
      },
    });

    expect(changed).toBe(true);
    expect(report.efficiency).toMatchObject({
      toolCalls: 5,
      duplicateToolCalls: 1,
      cacheHits: 3,
      tokenUsage: { input: 18, output: 7, reasoning: 3, cacheHit: 5 },
      maxCompactionLevel: 2,
      forcedSummary: true,
    });
    expect(report.dimensions.api).toMatchObject({
      efficiency: { duplicateToolCalls: 1, emptyRetries: 1 },
    });
    expect(report.totals).toMatchObject({
      efficiency: { cacheHits: 3, totalCompactedItems: 5 },
    });
  });

  test('exposes project skill delivery receipts in workflow reports', () => {
    const report = {
      version: '2.7.0',
      timestamp: '2026-05-24T00:00:00.000Z',
      project: { name: 'Alembic', files: 1, lang: 'ts' },
      duration: { totalMs: 100, totalSec: 0 },
      dimensions: { api: {} },
      totals: { skills: 1 },
      checkpoints: { restored: [] },
      incremental: null,
      semanticMemory: null,
      session: { id: 'session-1' },
    } as WorkflowReport;
    const receipt = createAlembicProjectSkillDeliveryReceipt({
      asset: {
        contentHash: 'sha256:abc123',
        dimensionId: 'api',
        path: '/tmp/project/Alembic/skills/project-api/SKILL.md',
      },
      authorization: {
        codexSkillRoot: '/tmp/project/.agents/skills',
        projectScopeId: 'project:test',
        status: 'pending',
      },
      codexSkillRoot: '/tmp/project/.agents/skills',
      createdAt: '2026-05-24T12:00:00Z',
      dimensionId: 'api',
      id: 'receipt-api',
      managedMarker: {
        generatedSkillId: 'alembic:project:test:project-api',
        markerPath: '/tmp/project/.agents/skills/project-api/.alembic-managed.json',
      },
      projectId: 'test',
      projectRoot: '/tmp/project',
      projectScopeId: 'project:test',
      runtimeExport: {
        codexSkillRoot: '/tmp/project/.agents/skills',
        projectScopeId: 'project:test',
        status: 'pending',
      },
      skillName: 'project-api',
    });

    const changed = augmentWorkflowReportWithSkillDeliveryReceipts(report, {
      created: 1,
      failed: 0,
      skills: ['project-api'],
      errors: [],
      deliveryReceipts: [receipt],
      deliveryReceiptSummaries: ['Project Skill project-api generated by Alembic'],
    });

    expect(changed).toBe(true);
    expect(report.projectSkillDelivery).toMatchObject({
      contract: 'ProjectSkillDeliveryReceipt',
      receiptCount: 1,
      route: 'alembic',
    });
    expect(report.totals).toMatchObject({ projectSkillDeliveryReceipts: 1 });
    expect(report.dimensions.api).toMatchObject({
      projectSkillDelivery: {
        receiptId: 'receipt-api',
        runtimeExportStatus: 'pending',
        skillName: 'project-api',
      },
    });
  });

  test('exposes PCV node-local baseline evidence in workflow reports', () => {
    const report = {
      version: '2.7.0',
      timestamp: '2026-05-28T00:00:00.000Z',
      project: { name: 'Alembic', files: 1, lang: 'ts' },
      duration: { totalMs: 100, totalSec: 0 },
      dimensions: { api: {} },
      totals: {},
      checkpoints: { restored: [] },
      incremental: null,
      semanticMemory: null,
      session: { id: 'session-1' },
    } as WorkflowReport;

    const changed = augmentWorkflowReportWithPcvNodeLocalBaseline(report, {
      api: {
        candidateCount: 1,
        durationMs: 10,
        pcvNodeEvidence: {
          n8: {
            chainNodeId: 'N8-stage-factory-tool-policy',
            contract: 'PCVColdStartNodeLocalBaseline',
            contractVersion: 1,
            dimensionId: 'api',
            evidenceKind: 'stage-factory-tool-policy',
            missingLinkReasons: [],
            nodeId: 'N8-stage-factory-tool-policy',
            producerToolRestriction: {
              gapLimit: null,
              noTerminalProof: true,
              producerStagePresent: true,
              requiredSubmitTool: 'knowledge',
              terminalToolIds: [],
            },
            sourceRefs: [],
            stageOrder: ['analyze', 'quality_gate', 'produce', 'rejection_gate'],
            stageToolPolicies: [],
            status: 'linked',
            summary: 'n8 linked',
            terminalCapabilityHints: {
              terminalCapability: {
                enabled: true,
                modes: ['run'],
                scriptAllowed: false,
                toolset: 'terminal-run',
              },
              constraints: [],
            },
          },
          n11: {
            acceptedCount: 1,
            chainNodeId: 'N11-produce',
            contract: 'PCVColdStartNodeLocalBaseline',
            contractVersion: 1,
            dimensionId: 'api',
            evidenceKind: 'producer-cut',
            gapLimit: null,
            missingLinkReasons: [],
            noTerminalProof: true,
            nodeId: 'N11-produce',
            producerOnlyCut: true,
            producerToolCalls: [{ action: 'submit', status: 'created', tool: 'knowledge' }],
            rejectedCount: 0,
            sourceRefs: ['src/api.ts'],
            status: 'linked',
            submittedCount: 1,
            summary: 'n11 linked',
            terminalToolCallCount: 0,
          },
        },
      },
    });

    expect(changed).toBe(true);
    expect(report.pcvScorecard).toMatchObject({
      contract: 'PCVColdStartNodeLocalBaseline',
      scope: 'alembic-cold-start-bootstrap-node-local',
      summary: { blockedNodes: 0, dimensionCount: 1, linkedNodes: 2, nodeCount: 2 },
    });
    expect(report.dimensions.api).toMatchObject({
      pcvNodeEvidence: {
        n8: { status: 'linked' },
        n11: { acceptedCount: 1, status: 'linked' },
      },
    });
    expect(report.totals).toMatchObject({
      pcvNodeLocalEvidenceDimensions: 1,
      pcvNodeLocalEvidenceNodes: 2,
      pcvNodeLocalLinkedNodes: 2,
    });
  });
});
